export const PLANS_ID= process.env.NEXT_PUBLIC_APPWRITE_PLANS_ID!
export const PROFILES_ID= process.env.NEXT_PUBLIC_APPWRITE_PROFILES_ID!
export const PROJECTS_ID= process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!
export const DATABASES_ID= process.env.NEXT_PUBLIC_APPWRITE_DATABASES_ID!
export const COMPONENTS_ID= process.env.NEXT_PUBLIC_APPWRITE_COMPONENTS_ID!
export const AI_REQUESTS_ID= process.env.NEXT_PUBLIC_APPWRITE_AI_REQUESTS_ID!
export const SUBSCRIPTIONS_ID= process.env.NEXT_PUBLIC_APPWRITE_SUBSCRIPTIONS_ID!